// <auto-generated />
using AllwynInPWA.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AllwynInPWA.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AllwynInPWA.Shared.Job", b =>
                {
                    b.Property<int>("JobID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EduLev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsExp")
                        .HasColumnType("int");

                    b.HasKey("JobID");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            JobID = 1,
                            EduLev = "Bachelor",
                            JobDesc = "Data Scientist will have necessary statistical modelling, mathematical, big data analytics and predictive modelling skills to build the required algorithms necessary to ask right questions and build objective visualizations and findings from it.Data Scientist will have knowledge of integrating multiple systems and datasets to provide new insights.Examples of required skillset: Prior experience working as a data architect and managing information schema for large organizations â€¢ Experience with big data analytic tools such as Hadoop, Hive, MapReduce, SPLUNK, Elastic Search â€¢ Understanding and good working knowledge of SQL and NoSQL; Experience in machine learning, statistical modelling, and predictive analysis; Extensive experience with a statistical programming language",
                            JobTitle = "Senior Data Scientist",
                            YearsExp = 7
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
